Introduce Options. We used an enum std::option::Option
However, Option can also be `None`. rust wants to ensure that the values
always get the correct type. As the book says:
  You have to convert an Option<T> to a T
  before you can perform T operations with it.

error[E0277]: cannot add `Option<u8>` to `u8`
 --> src/main.rs:5:17
  |
5 |     let sum = x + y;
  |                 ^ no implementation for `u8 + Option<u8>`
  |
  = help: the trait `Add<Option<u8>>` is not implemented for `u8`

For more information about this error, try `rustc --explain E0277`.