Match must exhaust all values.
In this case we forgot None, and rust throws an error

error[E0004]: non-exhaustive patterns: `None` not covered
   --> src/main.rs:8:11
    |
8   |     match x {
    |           ^ pattern `None` not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `Option<i32>`

For more information about this error, try `rustc --explain E0004`.